import { describe, expect, it } from 'vitest';
import { buildBrevoRequest, formatSubmittedAt, onRequestPost, validateContact } from '../functions/api/contact';
const good = { name:'Alex Shopper', email:'alex@example.com', message:'Hello there', website:'' };
describe('contact endpoint', () => {
  it('validates a correct submission',()=>expect(validateContact(good).ok).toBe(true));
  it('accepts a blank optional name',()=>expect(validateContact({...good,name:''}).ok).toBe(true));
  it('still requires email',()=>expect(validateContact({...good,email:''}).ok).toBe(false));
  it('rejects the honeypot',()=>expect(validateContact({...good,website:'spam'}).ok).toBe(false));
  it('rejects malformed email',()=>expect(validateContact({...good,email:'nope'}).ok).toBe(false));
  it('rejects empty and oversized messages',()=>{expect(validateContact({...good,message:''}).ok).toBe(false);expect(validateContact({...good,message:'x'.repeat(5001)}).ok).toBe(false)});
  it('rejects header injection',()=>expect(validateContact({...good,name:'Alex\r\nBcc:bad@example.com'}).ok).toBe(false));
  it('fails safely when environment is missing',async()=>{const request=new Request('https://example.com/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(good)});expect((await onRequestPost({request,env:{}})).status).toBe(503)});
  it('formats submission timestamps using readable Eastern time',()=>expect(formatSubmittedAt(new Date('2026-08-02T01:19:46.854Z'))).toBe('August 1, 2026 • 9:19 PM EDT'));
  it('builds the FloorsCalc-standard escaped HTML and plain-text email',()=>{const body=buildBrevoRequest({...good,name:'<Alex>'},{BREVO_API_KEY:'secret',CONTACT_TO_EMAIL:'to@example.com',CONTACT_FROM_EMAIL:'from@example.com'},'August 9, 2026 • 8:00 PM EDT');expect(JSON.stringify(body)).not.toContain('secret');expect(body.htmlContent).toContain('&lt;Alex&gt;');expect(body.htmlContent).toContain("Which Deal's Better?");expect(body.htmlContent).toContain('New contact form submission');expect(body.textContent).toContain("Website:\nWhich Deal's Better?");expect(body.textContent).toContain('Subject:\n(No subject provided)');expect(body.replyTo).toEqual({email:'alex@example.com',name:'<Alex>'})});
  it('uses the visitor email for Reply-To when name is omitted',()=>{const body=buildBrevoRequest({...good,name:''},{BREVO_API_KEY:'secret',CONTACT_TO_EMAIL:'to@example.com',CONTACT_FROM_EMAIL:'from@example.com'},'August 9, 2026 • 8:00 PM EDT');expect(body.replyTo).toEqual({email:'alex@example.com',name:'alex@example.com'});expect(body.htmlContent).toContain('Not provided');expect(body.textContent).toContain('Name:\nNot provided')});
  it('delivers a blank-name submission through the endpoint',async()=>{const originalFetch=globalThis.fetch;let delivery:any;globalThis.fetch=async(_url,init)=>{delivery=JSON.parse(String(init?.body));return new Response(null,{status:201})};try{const request=new Request('https://example.com/api/contact',{method:'POST',headers:{'content-type':'application/json','CF-Connecting-IP':'203.0.113.80'},body:JSON.stringify({...good,name:''})});expect((await onRequestPost({request,env:{BREVO_API_KEY:'secret',CONTACT_TO_EMAIL:'to@example.com',CONTACT_FROM_EMAIL:'from@example.com'}})).status).toBe(200);expect(delivery.replyTo).toEqual({email:'alex@example.com',name:'alex@example.com'});expect(delivery.textContent).toContain('Name:\nNot provided')}finally{globalThis.fetch=originalFetch}});
});
